### ISSUE TITLE
Robustness: decorate (transactional) fails when no hashmap item lookup

### ISSUE THREAD

**Issue by mkoertgen** [awesome-inc/neo4j-decorator#7]
Quick example using APOC and transactional endpoint revealed that the decorator fails when the hashmap for looking up decorations does not contain an item for the node label or edge type, i.e.

    decorator_1  | Debug: internal, implementation, error
    decorator_1  |     TypeError: Uncaught error: Cannot read property 'Person' of undefined
    decorator_1  |     at getDecorations (/usr/src/app/routes/graph.js:247:19)
    decorator_1  |     at _decorateDocumentFor (/usr/src/app/routes/graph.js:214:21)
    decorator_1  |     at _decorateDocumentTransactional (/usr/src/app/routes/graph.js:193:11)
    decorator_1  |     at _decorateDocumentTransactional (/usr/src/app/routes/graph.js:182:18)
    decorator_1  |     at _decorateDocumentTransactional (/usr/src/app/routes/graph.js:171:17)
    decorator_1  |     at _decorateDocumentTransactional (/usr/src/app/routes/graph.js:177:17)
    decorator_1  |     at _decorateDocumentTransactional (/usr/src/app/routes/graph.js:171:17)
    decorator_1  |     at _decorateDocument (/usr/src/app/routes/graph.js:119:20)
    decorator_1  |     at _decorateBody (/usr/src/app/routes/graph.js:105:10)
    decorator_1  |     at /usr/src/app/routes/graph.js:59:16

**Comment by mkoertgen** [comment]
Adding a `Person` item in the `decorate_transactional`-hashmap resolves this. However, the decorator should silently skip decorating for unknown graph objects,.
